### ISSUE TITLE
！！好用，提一个小的功能优化建议，供参考！！

### ISSUE THREAD

**Issue by flyinghmx** [ysyx2008/Organizer#2]
1.目前目录的命名是，是固定选的模式，能改为自定义吗？如：yyyy\yyyy-mm-dd\，类似于这样，短横线分割，年目录下的子目录直接到日期。
2.精准去重，能列出来，选择是否放到回收文件夹吗？ 相当于先不操作，先看看都有哪些重复的，再操作。
3.对文件，在分类的同时，能增加自动命名的功能吗？如图片是img_yyyymmdd_hhmmss.扩展名，视频是VID__yyyymmdd_hhmmss.扩展名，图片和视频可以都支持。

十分感谢。

**Comment by ysyx2008** [comment]
谢谢建议，逐个回复下：
第一个问题，其实有考虑过，技术上能实现，现在这种固定选的方式主要是为了降低使用门槛，帮助小白们解决问题。也许可以考虑增加一个自定义选项，保持固定格式，也允许自行设置，这样似乎更好。
第二个问题，如果列出来的话，一旦文件数量多可能比较难展示，还要再考虑下。目前去重后在日志文件里可以看到哪些照片是重复的。
第三个问题，一是使用门槛会高一点，二是有一些现成软件已经实现，所以没做。未来可以考虑。
